### ISSUE TITLE
Glitch problem on their website

### ISSUE THREAD

**Issue by hanzydev** [ProjectElixir-Devices/android_device_xiaomi_vili#1]
While browsing any website, the site glitches.

The browser I use: Google Chrome
Project Elixir release: Sun Jan 7 16:30:07 UTC 2024

**Comment by ThatMalayaliDeb** [comment]
i have switched to vulkan renderer. probably will be fixed in next release.
as a workaround for now, enable vulkan flag in google chrome flags
