### ISSUE TITLE
Refresh rate problem

### ISSUE THREAD

**Issue by hanzydev** [ProjectElixir-Devices/android_device_xiaomi_vili#2]
The refresh rate of the screen is set to 120Hz, but when I restart the phone or turn it off and on, the refresh rate drops and the screen lags a bit. If I change the refresh rate to 60Hz in the settings and then back to 120Hz, the problem is solved.

Project Elixir release: Sun Jan 7 16:30:07 UTC 2024

**Comment by ThatMalayaliDeb** [comment]
Never faced this problem in my device. nor have been reported by anyone before. please chec the modules installed and try disabling them.
